code refactored
Ellena557/smart-home-2019 pull request #2
Opened 2019-03-06 20:33 UTC by Ellena557

2019-03-08 12:25 UTC, iagoshkov requested changes
Переделайте в соответствии с замечаниями.
Уберите из git .class файлы, все что генерируется во время сборки проекта не должно жить в системе контроля версий, в ней храним только исходный код.

2019-03-08 12:25 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SensorEvent event = SensorEventCreator.getNextSensorEvent();
Здесь OCP нарушен. Как нам прикрутить другой/реальный EventСreator вместо Random?
Придется менять код тут. А надо сделать так, чтобы не приходилось - через интерфейс/реализацию.

2019-03-08 12:25 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +            SensorEventProcessor eventProcessor = EventProcessorCreator.getNewEventProcessor(smartHome, event);
Лучше eventProcessor-ы создать один раз и сложить в коллекцию, как мы сделали на занятии. А не создавать новый инстанс eventProcessor-а при получении события.
Это упростит логику. Если непонятно почему - напомните, на следующем занятии разберем.

2019-03-08 12:25 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/DoorEventProcessor.java
> +            // событие не от двери
else можно просто убрать, лишний код

2019-03-08 12:25 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/DoorEventProcessor.java
> +                            if (room.getName().equals("hall")) {
Проигрывание сценариев умного дома - это отдельная responsibility, как мы и обсуждали на занятии, нужно ее вынести в отдельный класс (отдельный eventprocessor).
Иначе при добавлении новых сценариев нам придется каждый раз менять код этого класса и встраивать новые if-ы и циклы.

2019-03-08 12:25 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/DoorEventProcessor.java
> +        if (event.getType() == DOOR_OPEN || event.getType() == DOOR_CLOSED){
Можно упростить и записать в одну строку:
`return event.getType() == DOOR_OPEN || event.getType() == DOOR_CLOSED`

2019-03-08 12:25 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/LightEventProcessor.java
> +        } else {
тоже можно просто убрать ветку else

2019-03-08 21:16 UTC, Ellena557 commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SensorEvent event = SensorEventCreator.getNextSensorEvent();
Все замечания исправила + еще в DoorEventProcessor, LightEventProcessor по функции добавила, чтобы то огромное количество скобочек немного сократить.

2019-03-10 18:06 UTC, iagoshkov approved these changes
В целом хорошо, одно замечание, которое в рамках 2-го ДЗ можно исправить.
Этот реквест можно вмержить в master.

2019-03-10 18:06 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +                SensorCommand command = new SensorCommand(CommandType.LIGHT_OFF, light.getId());
Плохая зависимость - у нас была доменная модель SmartHome которая не знала ничего про команды. И это было хорошо. Т.к. модель дома - абстракция, а команды, отправляемые оборудованию - уже ближе к деталям реализации. Мы раньше могли модель дома использовать в другом контексте (в другом, похожем, приложении), в котором например нет команд вообще. Теперь мы этого не можем, т.к. у нас модель SmartHome зависит от SensorCommand. Мы этим увеличили coupling.
Избавьтесь от этой зависимости.
В рамках второго ДЗ как раз подразумевается создание итератора и композита, которые позволят оставить логику итерации по внутренностям дома внутри дома, а действия над элементами дома объявить снаружи, например в самом EventProcessor-е.

2019-03-12 07:56 UTC, merged