homework-2
Ellena557/smart-home-2019 pull request #4
Opened 2019-03-13 19:30 UTC by Ellena557

2019-03-13 19:30 UTC, Ellena557 commented
Добрый вечер!
Это второй пул реквест, первый я закрыла, так как там при загрузке на гитхаб некоторые классы продублировались.

2019-03-16 14:54 UTC, iagoshkov requested changes
исправляйте по замечаниям

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/Components/Room.java
> +        // Можно через цикл for, можно через Iterator.
Лучше вообще через синтаксис java8 в две строчки:
lights.forEach(light -> light.execute(action);
doors.forEach(door -> door.execute(action);

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/DoorEventProcessor.java
> +        Door helpDoor = new Door(true, "1");
Не понял зачем это все нужно?
Зачем helpDoor, helpRoom, array?
Избавьтесь от них )))

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/DoorEventProcessor.java
> +                if (object.getClass() == helpDoor.getClass()){
здесь можно просто написать object instanceof Door

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/DoorEventProcessor.java
> +                if (object.getClass() == helpRoom.getClass()){
Зачем мы это сохраняем?

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/DoorEventProcessor.java
> +                if (object.getClass() == helpDoor.getClass()){
здесь можно просто написать object instanceof Door

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/DoorEventProcessor.java
> +                if (object.getClass() == helpRoom.getClass()){
Зачем мы это сохраняем?

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/DoorEventProcessor.java
> +                if (object.getClass() == helpRoom.getClass()){
Оно же потом нигде не используется?

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/HallDoorScenarioProcessor.java
> +        Door helpDoor = new Door(true, "1");
это не нужно

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/DoorEventProcessor.java
> +                if (object.getClass() == helpDoor.getClass()){
здесь можно просто написать object instanceof Door

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/DoorEventProcessor.java
> +                if (object.getClass() == helpRoom.getClass()){
Оно же потом нигде не используется?

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/HallDoorScenarioProcessor.java
> +        Door helpDoor = new Door(true, "1");
это не нужно

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/HallDoorScenarioProcessor.java
> +                if (object.getClass() == helpDoor.getClass()){
if (object instanceof Door) {

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/test/java/ru/sbt/mipt/oop/LightEventProcessorTest.java
> +    public static boolean lightIsOn(Light light){
ради такого не стоит делать метод )))
lightIsOn(light) не отличается от light.isOn()
второе даже лучше

2019-03-16 14:54 UTC, sbt-agoshkov commented on src/test/java/ru/sbt/mipt/oop/LightEventProcessorTest.java
> +        String kitchenId = "1";
такое ощущение что это id комнаты, а не света, а вы потом используете его как id источника света

2019-03-16 15:24 UTC, Ellena557 commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/DoorEventProcessor.java
> +        Door helpDoor = new Door(true, "1");
Это у нас на джаве было про getClass на той же неделе, так что первым делом пришло в голову:)

2019-03-16 15:25 UTC, Ellena557 commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/DoorEventProcessor.java
> +                if (object.getClass() == helpRoom.getClass()){
Это я пыталась сделать так, чтобы как и раньше при включении света выводилась еще и комната, но потом поняла, что нормальным способом это не делать (можно в execute разве что передавать два объекта), а удалить забыла.

2019-03-16 15:27 UTC, Ellena557 commented on src/test/java/ru/sbt/mipt/oop/LightEventProcessorTest.java
> +        String kitchenId = "1";
Да, это id источника света, просто я его назвала не очень. Исправила

2019-03-16 15:27 UTC, Ellena557 commented on src/main/java/ru/sbt/mipt/oop/Components/Room.java
> +        // Можно через цикл for, можно через Iterator.
Спасибо! Так действительно проще

2019-03-16 15:33 UTC, Ellena557 commented on src/test/java/ru/sbt/mipt/oop/LightEventProcessorTest.java
> +    public static boolean lightIsOn(Light light){
Исправила. Там еще такой же метод для двери был, его тоже убрала.

2019-03-19 21:28 UTC, iagoshkov approved these changes
Вроде все ок, только момент с выключением всего света через одну команду не очень как-то. См. комментарий

2019-03-19 21:28 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/HallDoorScenarioProcessor.java
>                          lightsOffCommand.executeCommand();
В прошлом ревью почему-то не заметил - у нас же нет команды сенсорам "выключить весь свет", мы можем только каждому источнику света отправлять команду индивидуально. Это вы так сильно упростили себе задачу.

2019-03-20 00:09 UTC, Ellena557 commented on src/main/java/ru/sbt/mipt/oop/EventProcessors/HallDoorScenarioProcessor.java
>                          lightsOffCommand.executeCommand();
Поняла, поменяю.

2019-03-20 14:59 UTC, merged