hw-3
Ellena557/smart-home-2019 pull request #5
Opened 2019-03-20 17:21 UTC by Ellena557

2019-03-20 17:21 UTC, Ellena557 commented
Третье задание + последняя правка по второму заданию про выключение всего света.

2019-03-23 13:15 UTC, iagoshkov requested changes
В целом более менее нормально, только не увидел, где AlarmDecorator, SmsDecorator и AlarmEventProcessor встраиваются в Application.
+ исправьте замечания, State немного недоделан

2019-03-23 13:15 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/AlarmService/AlarmActivatedState.java
> +        if (this.code.equals(enteredCode)){
У вас здесь есть ссылка на alarm.
У него внутри есть code.
Зачем вы здесь опять храните code?
Замените просто на вызов
`if (alarm.validateCode(enteredCode)) {`
и уберите поле code отсюда и из остальных состояний.

2019-03-23 13:15 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/AlarmService/Alarm.java
> +        state.printAlert();
здесь должен быть переход в AlarmAlertState

2019-03-23 13:15 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/AlarmService/Alarm.java
> +        state.printAlert();
ну т.е. нужно вызвать
`state.turnOnAlert();`

2019-03-23 13:15 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/AlarmService/AlarmState.java
> +    void printAlert();
не printAlert а "перейти в состояние alert"

2019-03-23 13:15 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void activateAlarm(String code){
Это не надо в дом выносить, иначе мы так много методов вынесем на верхний уровень.
Достаточно того, что есть getAlarm()

2019-03-23 13:15 UTC, sbt-agoshkov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +    public void deactivateAlarm(String code){
и это не надо

2019-03-23 19:02 UTC, Ellena557 commented
Поправила все эти замечания + еще то, о чем на семинаре говорили (у меня при вызове eventProcessors каждый раз прописывалось smartHome, убрала это).

2019-03-27 18:08 UTC, merged